name: video_watermark
description: Simple Flutter package to add image as overlay in the video along with video trim option.
homepage: https://github.com/lollipopkit/video_watermark.dart
repository: https://github.com/lollipopkit/video_watermark.dart

version: 1.0.5

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  ffmpeg_kit_flutter_min: ^6.0.3
  path_provider: ^2.0.11

platforms:
  android:
  ios:
